# Generated by Django 4.0.5 on 2022-06-29 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_testcases'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='topic_tag',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
