# Generated by Django 4.0.5 on 2022-06-29 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_problem_topic_tag'),
    ]

    operations = [
        migrations.RenameField(
            model_name='problem',
            old_name='problem_desc',
            new_name='desc',
        ),
        migrations.RenameField(
            model_name='problem',
            old_name='problem_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='problem',
            old_name='problem_status',
            new_name='status',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='user_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='user_rating',
            new_name='rating',
        ),
    ]
