# Generated by Django 4.0.5 on 2022-06-30 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_rename_problem_desc_problem_desc_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='problemId',
            field=models.IntegerField(null=True),
        ),
    ]
