# Generated by Django 4.0.5 on 2022-06-30 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_problem_problemid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='problem',
            name='problemId',
        ),
    ]
