# Generated by Django 4.0.5 on 2022-06-30 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_remove_problem_problemid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='desc',
            field=models.CharField(max_length=200),
        ),
    ]
