# Generated by Django 4.0.5 on 2022-07-03 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_alter_problem_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='difficulty',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
