# Generated by Django 4.0.6 on 2022-07-19 18:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_rename_userdetails_userdetail'),
    ]

    operations = [
        migrations.AddField(
            model_name='solution',
            name='username',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.userdetail'),
        ),
    ]
