# Generated by Django 4.0.6 on 2022-07-19 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_solution_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='solution',
            old_name='username',
            new_name='curr_user',
        ),
    ]
