# Generated by Django 4.0.6 on 2022-07-19 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_rename_username_solution_curr_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solution',
            name='curr_user',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
