# Generated by Django 4.0.6 on 2022-07-19 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_alter_solution_curr_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserDetail',
        ),
    ]
